"""Regenerate Rust fixtures from the local FilterPy reference implementation."""

from pathlib import Path

import numpy as np
from filterpy.kalman import (
    ExtendedKalmanFilter,
    KalmanFilter,
    MerweScaledSigmaPoints,
    UnscentedKalmanFilter,
)

MEASUREMENTS = (1.2, 1.85, 2.45)


def configure(filter_):
    filter_.x = np.array([0.2, 1.1])
    filter_.P = np.array([[2.0, 0.3], [0.3, 1.0]])
    filter_.Q = np.array([[0.02, 0.01], [0.01, 0.03]])
    filter_.R = np.array([[0.4]])
    return filter_


def linear():
    filter_ = configure(KalmanFilter(dim_x=2, dim_z=1))
    filter_.F = np.array([[1.0, 0.5], [0.0, 1.0]])
    filter_.H = np.array([[1.0, 0.0]])
    steps = []
    for measurement in MEASUREMENTS:
        filter_.predict()
        filter_.update(np.array([measurement]))
        steps.append((filter_.x.copy(), filter_.P.copy(), filter_.y.copy()))
    return steps


def extended():
    filter_ = configure(ExtendedKalmanFilter(dim_x=2, dim_z=1))
    filter_.F = np.array([[1.0, 0.5], [0.0, 1.0]])

    def hx(x):
        return np.array([x[0] ** 2 + 0.25 * x[1]])

    def h_jacobian(x):
        return np.array([[2.0 * x[0], 0.25]])

    steps = []
    for measurement in MEASUREMENTS:
        filter_.predict()
        filter_.update(np.array([measurement]), h_jacobian, hx)
        steps.append((filter_.x.copy(), filter_.P.copy(), filter_.y.copy()))
    return steps


def unscented():
    points = MerweScaledSigmaPoints(2, alpha=0.3, beta=2.0, kappa=0.0)

    def fx(x, _dt):
        return np.array(
            [x[0] + 0.5 * x[1] + 0.05 * x[0] ** 2, x[1] + 0.02 * np.sin(x[0])]
        )

    def hx(x):
        return np.array([x[0] ** 2 + 0.25 * x[1]])

    filter_ = configure(
        UnscentedKalmanFilter(dim_x=2, dim_z=1, dt=1.0, fx=fx, hx=hx, points=points)
    )
    steps = []
    for measurement in MEASUREMENTS:
        filter_.predict()
        filter_.sigmas_f = filter_.points_fn.sigma_points(filter_.x, filter_.P)
        filter_.update(np.array([measurement]))
        steps.append((filter_.x.copy(), filter_.P.copy(), filter_.y.copy()))
    return steps


def multivariate_linear():
    filter_ = KalmanFilter(dim_x=3, dim_z=2)
    filter_.x = np.array([0.5, -0.2, 1.0])
    filter_.P = np.array([[1.2, 0.1, 0.0], [0.1, 0.8, 0.2], [0.0, 0.2, 1.5]])
    filter_.F = np.array([[1.0, 0.2, 0.0], [0.0, 1.0, 0.3], [0.0, 0.0, 1.0]])
    filter_.Q = np.diag([0.01, 0.02, 0.03])
    filter_.H = np.array([[1.0, 0.0, 0.5], [0.0, 1.0, -0.25]])
    filter_.R = np.array([[0.3, 0.05], [0.05, 0.4]])
    steps = []
    for measurement in ([1.1, -0.1], [1.7, 0.05]):
        filter_.predict()
        filter_.update(np.asarray(measurement))
        steps.append((filter_.x.copy(), filter_.P.copy(), filter_.y.copy()))
    return steps


def rust_array(values):
    return ", ".join(repr(float(value)) for value in np.asarray(values).flat)


def main():
    output = ["// Generated by tests/generate_filterpy_reference.py; do not edit.\n"]
    cases = (
        ("LINEAR", linear),
        ("EXTENDED", extended),
        ("UNSCENTED", unscented),
        ("MULTIVARIATE_LINEAR", multivariate_linear),
    )
    for name, run in cases:
        steps = run()
        states = np.concatenate([state for state, _, _ in steps])
        covariances = np.concatenate([covariance.flat for _, covariance, _ in steps])
        innovations = np.concatenate([innovation for _, _, innovation in steps])
        output.append(
            f"pub const {name}_X: [f64; {states.size}] = [{rust_array(states)}];\n"
        )
        output.append(
            f"pub const {name}_P: [f64; {covariances.size}] = [{rust_array(covariances)}];\n"
        )
        output.append(
            f"pub const {name}_Y: [f64; {innovations.size}] = [{rust_array(innovations)}];\n"
        )
    output_path = Path(__file__).with_name("data") / "reference_data.rs"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text("".join(output))


if __name__ == "__main__":
    main()
